#!/usr/bin/env python3
import sys
import subprocess
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

_PYTHON_VENV = _VENV_DIR / "bin" / "python"

subprocess.check_call([_PYTHON_VENV, "-m", "wyoming_kokoro_torch"] + sys.argv[1:])